export const AUTH_EXPIRED_TOKEN = "auth/EXPIRED_TOKEN";
export const AUTH_SIGNED_IN = "auth/SIGNED_IN";
export const AUTH_SIGNED_OUT = "auth/SIGNED_OUT";

export const FIREBASE_NOTIFICATION_BACKGROUND_MESSAGE_CLICK =
  "firebaseNotification/BACKGROUND_MESSAGE_CLICK";
export const FIREBASE_NOTIFICATION_BACKGROUND_MESSAGE =
  "firebaseNotification/BACKGROUND_MESSAGE";
