services:
  project-name-web:
    networks:
      - dev-vn-networks
    container_name: project-name-web
    labels:
      - "traefik.enable=false"
    restart: always
    image: project-name-web-img:1.0.0
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  project-name-web-nginx:
    networks:
      - dev-vn-networks
    ports:
      - "project_external_port:80"
    container_name: project-name-web-nginx
    restart: always
    image: nginx:latest
    labels:
      - "traefik.docker.network=dev-vn-networks"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:project-domain.com,www.project-domain.com,abc.project-domain.com"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - project-name-web
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
networks:
  dev-vn-networks:
    external: true
